### ISSUE TITLE
[Bug] Toggle state is wrong sometimes

### ISSUE THREAD

**Issue by Dexwell** [merdok/homebridge-webos3#7]
Thanks for the fantastic plugin. 

Sometimes the toggle says my TV it's on when it's not. Can this be fixed?

**Comment by merdok** [comment]
Should be fixed with version 0.8.3!
Please let me know if it works better now!

**Comment by Dexwell** [comment]
Seems to work great so far 🙌🏼

**Comment by merdok** [comment]
Good to hear! Thanks for the info!

**Comment by Dexwell** [comment]
Hmm, seems it isn't completely fixed after all. Siri says the TV is on when turned off with the remote.

**Comment by merdok** [comment]
I could reproduce the issue once with my setup, but after i asked Siri the second time right after the first one, then Siri announced the correct state. 
Anyway i will check that out and see if i can improve it even further.

**Comment by Dexwell** [comment]
Yeah, HomeKit probably does the same state 'Updating' after the first voice command.

**Comment by merdok** [comment]
The TV doesn't sends out any signal to homebridge after it was turned off with the remote that is why the state needs to be checked every time the user requests the tv state. I believe the issue with siri is that it just lags the first time when she is asked about the tv state. 
But still, this should not happen and i will check out if i can come up with a solution for that. I am currently busy, but i will check it out next week.

**Comment by georgkreimer** [comment]
The homebridge-yeelight plugin has a heartbeat that checks the status of the WiFi lamp every 10secs. Maybe this helps with building a solution: https://github.com/vvpossible/homebridge_yeelight/blob/master/yeelight/lib/yee.js#L90

**Comment by merdok** [comment]
Thanks for that. Will check it out!

**Comment by merdok** [comment]
I did some modifications, hopefully this is fixed now with the last release.
